INFO 2023-10-24 16:14:23,137 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:15:09,660 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:18:42,102 autoreload 266 C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\urls.py changed, reloading.
INFO 2023-10-24 16:18:43,581 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:20:08,349 autoreload 266 C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\urls.py changed, reloading.
INFO 2023-10-24 16:20:09,897 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:21:03,842 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 16:21:05,295 log 241 Not Found: /
WARNING 2023-10-24 16:21:05,296 basehttp 212 "GET / HTTP/1.1" 404 2167
INFO 2023-10-24 16:21:10,103 basehttp 212 "GET /log HTTP/1.1" 301 0
ERROR 2023-10-24 16:21:10,171 log 241 Internal Server Error: /log/
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\urls.py", line 23, in log
    import loging
ModuleNotFoundError: No module named 'loging'
ERROR 2023-10-24 16:21:10,172 basehttp 212 "GET /log/ HTTP/1.1" 500 69074
INFO 2023-10-24 16:22:06,886 autoreload 668 Watching for file changes with StatReloader
ERROR 2023-10-24 16:22:12,557 log 241 Internal Server Error: /log/
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\urls.py", line 23, in log
    import loging
ModuleNotFoundError: No module named 'loging'
ERROR 2023-10-24 16:22:12,559 basehttp 212 "GET /log/ HTTP/1.1" 500 69062
INFO 2023-10-24 16:22:39,829 autoreload 266 C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\urls.py changed, reloading.
INFO 2023-10-24 16:22:41,394 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:23:14,057 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:23:14,591 urls 27 用户登陆了
WARNING 2023-10-24 16:23:14,591 urls 28 redis缓存不足
ERROR 2023-10-24 16:23:14,592 urls 29 该记录不存在
INFO 2023-10-24 16:23:14,592 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2023-10-24 16:45:48,850 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 16:59:24,974 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 17:02:18,943 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-24 17:05:34,186 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 17:05:41,149 log 241 Not Found: /
WARNING 2023-10-24 17:05:41,150 basehttp 212 "GET / HTTP/1.1" 404 2167
WARNING 2023-10-24 17:06:13,406 log 241 Not Found: /
WARNING 2023-10-24 17:06:13,406 basehttp 212 "GET / HTTP/1.1" 404 2167
WARNING 2023-10-24 17:07:00,372 log 241 Not Found: /
WARNING 2023-10-24 17:07:00,373 basehttp 212 "GET / HTTP/1.1" 404 2167
INFO 2023-10-24 17:09:27,390 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 17:09:38,838 log 241 Not Found: /
WARNING 2023-10-24 17:09:38,839 basehttp 212 "GET / HTTP/1.1" 404 2173
WARNING 2023-10-24 17:09:39,010 log 241 Not Found: /favicon.ico
WARNING 2023-10-24 17:09:39,011 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2224
INFO 2023-10-24 17:09:44,826 basehttp 212 "GET /log HTTP/1.1" 301 0
INFO 2023-10-24 17:09:44,848 urls 27 用户登陆了
WARNING 2023-10-24 17:09:44,848 urls 29 redis缓存不足
ERROR 2023-10-24 17:09:44,849 urls 30 该记录不存在
INFO 2023-10-24 17:09:44,849 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2023-10-24 17:21:19,780 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 17:21:21,715 log 241 Not Found: /
WARNING 2023-10-24 17:21:21,717 basehttp 212 "GET / HTTP/1.1" 404 2167
WARNING 2023-10-24 17:21:22,011 log 241 Not Found: /favicon.ico
WARNING 2023-10-24 17:21:22,012 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2218
INFO 2023-10-24 17:21:33,438 urls 27 用户登陆了
WARNING 2023-10-24 17:21:33,440 urls 29 redis缓存不足
ERROR 2023-10-24 17:21:33,441 urls 30 该记录不存在
INFO 2023-10-24 17:21:33,442 basehttp 212 "GET /log/ HTTP/1.1" 200 3
WARNING 2023-10-24 17:21:33,749 log 241 Not Found: /favicon.ico
WARNING 2023-10-24 17:21:33,751 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2224
INFO 2023-10-24 17:21:37,003 basehttp 212 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-24 17:21:37,201 basehttp 212 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-10-24 17:21:37,771 basehttp 212 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2023-10-24 17:21:37,772 basehttp 212 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2023-10-24 17:21:37,774 basehttp 212 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-24 17:21:37,775 basehttp 212 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2023-10-24 17:21:37,778 basehttp 212 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-24 17:21:37,784 basehttp 212 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2023-10-24 17:21:37,810 basehttp 212 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2023-10-24 17:26:04,591 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 17:26:07,297 log 241 Not Found: /
WARNING 2023-10-24 17:26:07,298 basehttp 212 "GET / HTTP/1.1" 404 2167
INFO 2023-10-24 17:26:20,801 urls 27 用户登陆了
WARNING 2023-10-24 17:26:20,802 urls 29 redis缓存不足
ERROR 2023-10-24 17:26:20,802 urls 30 该记录不存在
INFO 2023-10-24 17:26:20,803 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2023-10-24 17:37:21,305 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-24 17:37:21,818 log 241 Not Found: /
WARNING 2023-10-24 17:37:21,818 basehttp 212 "GET / HTTP/1.1" 404 2167
WARNING 2023-10-24 17:37:22,948 log 241 Not Found: /
WARNING 2023-10-24 17:37:22,949 basehttp 212 "GET / HTTP/1.1" 404 2167
INFO 2023-10-24 17:37:31,028 urls 27 用户登陆了
WARNING 2023-10-24 17:37:31,029 urls 29 redis缓存不足
ERROR 2023-10-24 17:37:31,029 urls 30 该记录不存在
INFO 2023-10-24 17:37:31,030 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2023-10-25 10:35:29,005 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-25 10:37:03,795 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-10-25 10:37:17,123 log 241 Not Found: /
WARNING 2023-10-25 10:37:17,124 basehttp 212 "GET / HTTP/1.1" 404 2167
WARNING 2023-10-25 10:37:17,384 log 241 Not Found: /favicon.ico
WARNING 2023-10-25 10:37:17,385 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2218
INFO 2023-10-25 10:37:28,102 basehttp 212 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-25 10:37:28,274 basehttp 212 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-10-25 10:37:28,363 basehttp 212 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2023-10-25 10:37:28,366 basehttp 212 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2023-10-25 10:37:28,367 basehttp 212 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2023-10-25 10:37:28,367 basehttp 212 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-25 10:37:28,370 basehttp 212 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-25 10:37:28,377 basehttp 212 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2023-10-25 10:37:28,390 basehttp 212 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
ERROR 2023-10-25 10:37:30,752 log 241 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'duoduoshop.auth_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\generic\edit.py", line 152, in post
    if form.is_valid():
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\forms\forms.py", line 434, in full_clean
    self._clean_form()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\forms\forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\auth\forms.py", line 242, in clean
    self.user_cache = authenticate(
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\auth\__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\auth\backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\contrib\auth\base_user.py", line 54, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'duoduoshop.auth_user' doesn't exist")
ERROR 2023-10-25 10:37:30,776 basehttp 212 "POST /admin/login/?next=/admin/ HTTP/1.1" 500 260192
INFO 2023-10-25 10:37:37,890 basehttp 212 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-10-25 10:39:14,753 autoreload 266 C:\Users\guota\OneDrive\桌面\duoduo_project\duoduoshop\duoduoshop\settings.py changed, reloading.
INFO 2023-10-25 10:39:16,358 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-25 10:40:18,391 autoreload 668 Watching for file changes with StatReloader
ERROR 2023-10-25 10:42:32,929 exception 124 Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
WARNING 2023-10-25 10:42:33,018 log 241 Bad Request: /log/
WARNING 2023-10-25 10:42:33,019 basehttp 212 "GET /log/ HTTP/1.1" 400 72182
ERROR 2023-10-25 10:42:33,358 exception 124 Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
WARNING 2023-10-25 10:42:33,401 log 241 Bad Request: /favicon.ico
WARNING 2023-10-25 10:42:33,402 basehttp 212 "GET /favicon.ico HTTP/1.1" 400 72116
ERROR 2023-10-25 10:43:05,304 exception 124 Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\guota\Envs\duoduoshop\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'duoduoshop.site:8000'. You may need to add 'duoduoshop.site' to ALLOWED_HOSTS.
WARNING 2023-10-25 10:43:05,347 log 241 Bad Request: /favicon.ico
WARNING 2023-10-25 10:43:05,348 basehttp 212 "GET /favicon.ico HTTP/1.1" 400 72116
INFO 2023-10-25 10:43:15,590 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-25 10:43:22,569 urls 27 用户登陆了
WARNING 2023-10-25 10:43:22,569 urls 29 redis缓存不足
ERROR 2023-10-25 10:43:22,571 urls 30 该记录不存在
INFO 2023-10-25 10:43:22,572 basehttp 212 "GET /log/ HTTP/1.1" 200 3
WARNING 2023-10-25 10:43:22,739 log 241 Not Found: /favicon.ico
WARNING 2023-10-25 10:43:22,740 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2224
INFO 2023-10-25 10:43:54,433 autoreload 668 Watching for file changes with StatReloader
INFO 2023-10-25 10:43:57,928 urls 27 用户登陆了
WARNING 2023-10-25 10:43:57,928 urls 29 redis缓存不足
ERROR 2023-10-25 10:43:57,928 urls 30 该记录不存在
INFO 2023-10-25 10:43:57,929 basehttp 212 "GET /log/ HTTP/1.1" 200 3
WARNING 2023-10-25 10:43:58,100 log 241 Not Found: /favicon.ico
WARNING 2023-10-25 10:43:58,100 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2228
WARNING 2023-10-25 10:45:57,794 log 241 Not Found: /
WARNING 2023-10-25 10:45:57,795 basehttp 212 "GET / HTTP/1.1" 404 2167
INFO 2023-10-25 10:46:05,153 urls 27 用户登陆了
WARNING 2023-10-25 10:46:05,153 urls 29 redis缓存不足
ERROR 2023-10-25 10:46:05,153 urls 30 该记录不存在
INFO 2023-10-25 10:46:05,153 basehttp 212 "GET /log/ HTTP/1.1" 200 3
